### PR TITLE
Replace gnulib stdint.h with CHERI aware version

### PR DESCRIPTION
**Pull request by brooksdavis**
If a port contains stdint.in.h from gnulib and it does not contain fixes for CHERI, replace it with an upstream version that does. This version corresponds to gnulib commit 6e4aa95cc6f165d2d3a30e963f13596e6b09ed90.

Fixes: #129

### CODE REVIEW

**Comment by brooksdavis** [comment]
I've verified that this version lets me build devel/gettext-tools.

**Comment by kwitaszczyk** [comment]
Could we split the commit that introduces Templates/gnulib/stdint.in.h into two commits: one that imports the file from upstream and one that modifies the file to support CHERI? This would make it easier to understand what changed, in particular when updating stdint.in.h in the future.

We can also revert c0f8ed299fac8d60261c23fee223163d5806b2bb now.

**Review by kwitaszczyk — COMMENTED** [review]
Could we split the commit that introduces Templates/gnulib/stdint.in.h into two commits: one that imports the file from upstream and one that modifies the file to support CHERI? This would make it easier to understand what changed, in particular when updating stdint.in.h in the future.

We can also revert c0f8ed299fac8d60261c23fee223163d5806b2bb now.

**Comment by brooksdavis** [comment]
> Could we split the commit that introduces Templates/gnulib/stdint.in.h into two commits: one that imports the file from upstream and one that modifies the file to support CHERI? This would make it easier to understand what changed, in particular when updating stdint.in.h in the future.

I've updated the commit message to clarity that this is a completely unmodified upstream version.

> We can also revert [c0f8ed2](https://github.com/CTSRD-CHERI/cheribsd-ports/commit/c0f8ed299fac8d60261c23fee223163d5806b2bb) now.

Done.

**Review by kwitaszczyk — APPROVED** [review]
Thanks!

**Pull request merged**
