### PR TITLE
Add nginx-cheri port.

### PR DESCRIPTION
**Pull request by qwattash**
This is the CHERI purecap nginx port with support for sub-object bounds.
The package has two flavors: the 'default' flavor does not use sub-object bounds; the 'subobject' flavor enables sub-object bounds.

### CODE REVIEW

**Comment by jrtc27** [comment]
I would like `pkg64c install nginx` to do the right thing. Whether that means patching the real nginx port or hijacking it with a port which produces an identically-named package I don't really care.

**Comment by jrtc27** [comment]
See gdb-meta for an example of hijacking the port, though I don't know if we need the indirection here. We don't really need it for gdb either other than presumably for upgrades to work?

**Comment by qwattash** [comment]
I have done some reworking, however I need to test this with hybrid builds and poudriere.

**Review by kwitaszczyk — CHANGES_REQUESTED** [review]
The changes look fine but they seem to be mixed across commits. Could you move changes in www/nginx-cheri into a single commit? At least the commit messages suggest that was the intention.

Also, could you clarify in the commit message how CheriBSD.patch was generated? If it was just `git diff` between an upstream version and a CHERI-extended branch, a reference to the CHERI-extended branch would be sufficient. It'd be important to guarantee that the referenced branch stays in the fork repository. I know there are various branches in CTSRD-CHERI/nginx and it might be worth cleaning up those branches first to have a single reference branch with CHERI extensions rather than multiple ones that confuse people, if they're not needed.

**Review by kwitaszczyk — CHANGES_REQUESTED** [review]
Could you fix the commit
> www/nginx: Hijack the www/nginx port to build www/nginx-cheri.
to describe www/nginx-meta instead of www/nginx?

Also,
> www/nginx-cheri: Add nginx-cheri port.
includes www/nginx-meta whilst the other commit actually aims to describe it. I believe www/nginx-meta should be moved there.

When adding a port, it must be added to its category's Makefile. www/Makefile does not currently list www/nginx-meta and www/nginx-cheri.

**Review by kwitaszczyk — APPROVED** [review]
Thanks!

**Pull request merged**
